Run mkdir -p src
  mkdir -p src
  if [ ! -f src/HELLO.cob ]; then
    cat > src/HELLO.cob <<'EOF'
         IDENTIFICATION DIVISION.
         PROGRAM-ID. HELLO.
  
         PROCEDURE DIVISION.
             DISPLAY "HELLO FROM OTTERKIT GITHUB ACTIONS".
             STOP RUN.
    EOF
  fi
  ls -la src
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /usr/share/dotnet
/home/runner/work/_temp/bbf30644-d727-41f6-aa76-84e6cb4ecad6.sh: line 12: warning: here-document at line 3 delimited by end-of-file (wanted `EOF')
/home/runner/work/_temp/bbf30644-d727-41f6-aa76-84e6cb4ecad6.sh: line 13: syntax error: unexpected end of file
Error: Process completed with exit code 2.